spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafe_db?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 12345

#ai-server:
#url: "" 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  
  mvc:
    async:
      request-timeout: -1

kakao:
  rest-api-key: 4237d5d50ad473790cfcb04a8f17608e
  client-secret: AXyKoe9feMZDJsdXoAvceFU9ItP1OOQ8
  redirect-uri: http://34.64.58.23:8080/api/kakao/callback
  frontend-url: http://localhost:3000/dashboard/system-settings

weather:
  api-key: 42411751ff40b6ec545dd37e1ce13dba
  city: Changwon
  country: KR

gemini:
  api-key: AIzaSyAQ.Ab8RN6KNv294ajVWarbl8HqQL_2Y51MO5HQOAlheCbn_Sem_Wg

naver:
  client-id: BkZDAWlQBySFIKgxLwLi
  client-secret: iF7REL4C5y